# Generated by Django 3.1.7 on 2021-03-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetables.timetable'),
            preserve_default=False,
        ),
    ]
