# Generated by Django 3.1.7 on 2021-03-17 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210317_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 12, 44, 12, 353830, tzinfo=utc), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
