# Generated by Django 3.1.7 on 2021-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_subject'),
        ('profiles', '0005_profile_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(to='classes.Subject'),
        ),
    ]
