# Generated by Django 3.1.7 on 2021-03-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='materials/')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tuition_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.tuitionclass')),
            ],
        ),
    ]
