# Generated by Django 3.1.7 on 2021-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='tutition_class',
            new_name='tuition_class',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.IntegerField(default=0),
        ),
    ]
