# Generated by Django 3.1.7 on 2021-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_auto_20210317_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
