# Generated by Django 3.1.7 on 2021-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_auto_20210317_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='in_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
